### ISSUE TITLE
Is this "News search", not a document search?

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/MatchItFast#5]
As it uses GDELT as the source of the document search, it looks like the demo works well on news articles, but not work well for other generic documents. If the document search model is trained with news articles, only, can we change the name to "News Search"? Also, it would be great if the search UI page has a link to Google News so the users easily pick one of the news article for try out.

**Comment by nagachika** [comment]
Add a link to Google News is a great idea! I have implemented and deployed these changes.

I have once considered to add a selector for the builtin query texts in the News search page as in the Image Search page. I gaveup the selectors because of the concerns about the copyright, and also the difficulity to select the news articles proper in the all situations.

**Comment by kazunori279** [comment]
Thanks for the update! 

Currently the UI looks like this:

- Enter query text
- You can find the latest news articles from Google News.

This UI is a little confusing.. "query text" should mean an article text, and also "find" sounds like you can find Google News article with this demo.

So, how about this?

- Enter a news article text to search
- You may copy & paste some paragraphs from Google News articles

**Comment by nagachika** [comment]
Thank you! I changed wording in the news search UI.
